### ISSUE TITLE
[tracking] Align bitmanip implementation with latest version of the spec

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/ibex#1470]
Currently, Ibex optionally implements draft version 0.92 of the RISC-V Bitmanip spec. We want to re-align the implementation with the updated specification v.1.0.0 (Zba, Zbb, Zbc, Zbs sub extensions) and draft version 0.93 (Zbf, Zbt, Zbe, Zbp, Zbr sub extensions). To this end, the following tasks need to be done:

- [x] Zba: implementation, see #1422
- [x] Zbb: see #1476 
  - [x] Move slo[i] and sro[i] instructions to Zbp (0.93).
  - [x] Remove rev. This instruction isn’t part of Zbb anymore. It’s part of grev[i] which is included in Zbp (Ibex “Full” only). The rev8 instruction remains part of Zbb.
  - [x] Rename pcnt to cpop.
  - [x] Move sext.[bh] from Zb_temp to Zbb (classification was ambiguous in 0.92)
- [x] Zbs: Rename sb* instructions (sbset[i], sbclr[i], sbinv[i], sbext[i])  to b*, see #1476
- [x] Zbe: Rename bext/bdep to bcompress/bdecompress (technically only 0.94, but needed as in 0.93 there exist two different instructions named bext otherwise), see #1476 
- [x] Zbp: Implement xperm.[nbh], see #1483
- [x] Add a new config to enable everything except for Zbe, see #1493 

- [x] Verification/RISCV-DV:
  - [x] Merge PR adding support for v.1.0.0, see google/riscv-dv#832
  - [x] Enable support for both v.1.0.0 and v.0.93 at the same time, currently exclusive (only sub-extensions not part of v.1.0.0), see see google/riscv-dv#834
  - [x] Update Spike version, the [one modified by Greg for the cosim framework](https://github.com/lowRISC/riscv-isa-sim/tree/ibex_cosim) is working (at least for v.1.0.0), #1530
  - [x] Re-enable bitmanip tests  #1532
- [x] GCC/LLVM compiler toolchains:  #1529
  - [x] [GCC 10.2.0 with RVB support](https://github.com/riscv-collab/riscv-gcc/tree/riscv-gcc-10.2.0-rvb) works for v.1.0.0, not sure about v.0.93 in that GCC version
  - [x] [Latest RISC-V binutils](https://github.com/riscv-collab/riscv-binutils-gdb/commit/b69c9d41e89498442cb5af5287f378b3583dd445) works for v.1.0.0, not sure about v.0.93 with that version of binutils

**Comment by vogelpi** [comment]
The remaining tasks have now been handled by @luismarques and @rswarbrick , I am thus closing this issue. Thanks guys!
