### ISSUE TITLE
[dv, fcov] Outstanding fcov implementation tracking

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1598]
Required coverage points are listed in the [Ibex Coverage Plan](https://ibex-core.readthedocs.io/en/latest/03_reference/coverage_plan.html).

Where coverage is implemented a coverpoint or cross name is listed in the documentation.

The following coverage still needs to be implemented. The descriptions are copied from the coverage plan. It is broken down by coverage plan section. See the coverage plan for further details

**Hazards**
- [x] #1601

**State Specific Behaviour**
- [x] Loads/stores with `mstatus.mprv` set and unset.

**PMP**
- [x] PMP region access pass/fail with all combinations of unaligned access split across a boundary, both halves pass, neither pass, just the first passes, just the second passes.
- [x] Compressed instruction access (16-bit) passes PMP but 32-bit access at same address crosses PMP region boundary.
- [x] Each field of mssecfg enabled/disabled with relevant functionality tested.
- [x] Access close to PMP region modification that allows/disallows that access

**CSRs**
- [x] Write illegal/unsupported value to WARL field.
- [x] Read and write from/to an unimplemented CSR

**Exceptions/Interrupts/Debug**
 - [x] #1664

**Miscellaneous**
- [x] Double fault
- [x] Awake from sleep due to interrupt or debug
- [x] Interrupt/Debug whilst entering sleep.
- [x] Enabling/Disabling ICache

**Cross Coverage**
- [x] Instruction Categories x Controller state transitions of interest

**Comment by johngt** [comment]
Given that the related issue #1564 is in the V2 Milestone, tagged this with V2.

**Comment by ctopal** [comment]
Closing this one as all outstanding functional coverage implementation is done and reviewed.
