### ISSUE TITLE
[dv] Ibex V2 Actions

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1901]
- [x] #1902
  - [x] Fix bitmanip coverage collection - https://github.com/google/riscv-dv/pull/910
  - [x] Look into other holes, check there's nothing vital missing - https://github.com/lowRISC/ibex/issues/1925
  - [x] https://github.com/lowRISC/ibex/pull/1929
  - [x] https://github.com/lowRISC/ibex/pull/1930
- [x] Complete internal interrupt work #1907
- [x] #1903, https://github.com/lowRISC/ibex/issues/1944
- [x] Complete iCache functional coverage work  - #1649, #1923
- [x] Add double fault checking assertion - #1760, #1916
- [x] Assert in OT earlgrey to ensure correct connectivity for fetch enable - https://github.com/lowRISC/opentitan/issues/15217
- [x] Assert to check crash dump output - https://github.com/lowRISC/opentitan/issues/15427, https://github.com/lowRISC/ibex/pull/1924
- [x] #1904, https://github.com/lowRISC/ibex/pull/1939
  - [x] Link from OT docs  
  - [x] Explain PMP coverage/verification is better closed by formal techniques or different test generation strategies but the current setup is sufficient for V2
- [x] #1905 - https://github.com/lowRISC/ibex/pull/1928
