### ISSUE TITLE
Create page tracking tape out information (and maybe comparison?)

### ISSUE THREAD

**Issue by mithro** [lowRISC/ibex#309]
It would be awesome if you had a "information from tape outs" type page in the documentation somewhere. I would like to see it have the following information;

 - [ ] What was taped out
 - [ ] Who it was taped out with (IE Foundry, Node, PDK, Process, etc)
 - [ ] What type of tape out it was, test chip, production run, etc....
 - [ ] What tools were used
 - [ ] What was the resulting gate count
 - [ ] What was the resulting silicon area usage (mm x mm)
 - [ ] Some performance / energy specs.

The idea is to quickly get an idea for;
 - [ ] How frequently the core is being taped out.
 - [ ] What the most popular way to tape out the IC is (who is being used, what node, etc)
 - [ ] Ballpark around expected size and performance

There is some great information in the "Slow and Steady Wins the Race? A Comparison of
Ultra-Low-Power RISC-V Cores for Internet-of-Things Applications" paper you link too. However, it would be good to have a quick summary to look at.

FYI The information from that paper says;
> Zero-riscy is 2.2× smaller than Riscy and provides a 2× energy boost for mixed control/arithmetic code with limited DSP. Micro-riscy is 1.6× smaller than Zero-riscy (∼11.6 kgates in UMC 65nm), has a power envelope of just 100μW at 160MHz and it is 1.4× more energy efficient than Zero-riscy on pure control code.

**Comment by rswarbrick** [comment]
@tomroberts-lowrisc: You added some area numbers to our documentation recently, right? Unless there are people taping out Ibexen without telling us, I think the proposed table would be pretty short. Is there anything left in this suggestion that would be worth doing?
