### ISSUE TITLE
[tracking] Use Verible for lint

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#579]
We want to use verible_lint (https://github.com/google/verible) as one of our lint tools. There are a couple things to be solved first.

A run of Verible today shows that most lint rules match our use of SV, with the exception of localparam naming (which verible_lint expects to be UpperCamelCase, while we go for ALL_CAPS).

- [x] Extend edalize to support verible: https://github.com/olofk/edalize/issues/95
- [x] Add Verible as a lint target to our .core files: #686 
- [x] Add Verible in non-enforcing mode to CI.  #686 

If we want to run Verible in "enforcing" mode (e.g. in CI) we additionally need:
- [x] Waiver support: https://github.com/google/verible/issues/105
- [x] parse error for define-to-string conversions: https://github.com/google/verible/issues/166
- [ ] string parameters without type: https://github.com/google/verible/issues/167 or waivers. #735 

Optional, but very helpful:
- [x] Have pre-compiled binaries of verible available. Verible requires a C++17-capable compiler, which typically isn't available by default in our supported platforms, e.g. RHEL7. Binaries are statically linked, so should be reasonably easy to distribute. Opened https://github.com/google/verible/issues/168 to see if that's something that Verible can provide us with.
- [ ] Use config files #736 

CC @fangism @msfschaffner @mithro

**Comment by msfschaffner** [comment]
The localparam discrepancy is somewhat unfortunate. Initially, the lowRISC style guide was based on the one that Verible uses, but it looks like we have diverged here. Currently, the lowRISC style makes the distinction depending on whether the parameter/localparam is to be interpreted as an immutable constant or not. The style that Verible follows makes the distinction based on whether it is a localparam or a parameter. One way would be to align the style here, but the optimum would of course be configuratbility...

**Comment by imphil** [comment]
@msfschaffner You can find the full motivating discussion on the current localparam style guide at https://github.com/lowRISC/stwg-base/issues/427 (Sorry for all non-OpenTitan readers, this issue isn't public. I can copy over content if you're really interested.)

**Comment by imphil** [comment]
A couple more things on the Verible front to be fixed, but none of them are blockers:

- https://github.com/google/verible/issues/343
- https://github.com/google/verible/issues/341
- https://github.com/google/verible/issues/344

https://github.com/olofk/edalize/pull/178 is the enablement on the edalize front, and #999 are the remaining fixes on Ibex.
