### ISSUE TITLE
[tracking] Questa issues

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#671]
Questa issues reported in #622 by @danghai 

- [x] #669 (Questa complains about newlines in ASSERT macros)
- [x] #670 (Questa: Defaulting port to var rather than wire)
- [x] https://github.com/lowRISC/ibex/issues/696:

**Comment by danghai** [comment]
I try to run the full flow in `Makefile`. I got the result so far:
[regr.log](https://github.com/lowRISC/ibex/files/4313779/regr.log)
Compile and Optimize log:
[qrun_compile_optimize.log](https://github.com/lowRISC/ibex/files/4313790/qrun_compile_optimize.log)
1 sample Sim log (all are the same, 2 warning messages)
[sim.log](https://github.com/lowRISC/ibex/files/4313794/sim.log)

**Comment by imphil** [comment]
The current master should have all outstanding issues resolved, can you double-check if the Questa runs are now warning-free @danghai?

**Comment by danghai** [comment]
Hi @imphil . It is now warning-free. I believe that you can close the issue. Thank you

**Comment by imphil** [comment]
Great, thanks!
